backend:
  name: github
  repo: jundi14/myblog-revisi
media_folder: static/img
public_folder: /img
commit_messages:
  create: Create {{collection}} “{{slug}}”
  update: Update {{collection}} “{{slug}}”
  delete: Delete {{collection}} “{{slug}}”
  uploadMedia: Upload “{{path}}”
  deleteMedia: Delete “{{path}}”
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}-{{day}}-{{month}}-{{year}}'
    editor:
      preview: false
    fields:
      - { label: 'Judul Artikel', name: 'title', widget: 'string' }
      - { label: 'Custom URL', name: 'slug', widget: 'string' }
      - { label: 'Tanggal Posting', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - label: "Kategori"
        name: "categories"
        widget: "select"
        multiple: true
        options: ["Teknologi", "Blogging", "Coretan"]
        default: ["Teknologi"]
      - { label: 'cover', name: 'cover', widget: 'image', required: false }
      - { label: 'Komentar', name: 'comment', widget: 'boolean', required: false }
      - { label: 'Artikel', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    folder: 'content'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Judul Halaman', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }      
      - { label: 'Isi Halaman', name: 'body', widget: 'markdown' }
    
